-- ZakiChat message attachment storage

insert into storage.buckets (
  id,
  name,
  public
)
values (
  'message-attachments',
  'message-attachments',
  false
)
on conflict (id) do update
set public = false;

-- Users may upload attachments into their own folder:
-- message-attachments/<user-id>/...

drop policy if exists "Users can upload message attachments"
on storage.objects;

create policy "Users can upload message attachments"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'message-attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- Users may read attachments belonging to conversations
-- through signed URLs generated by the application.
-- Direct object reads are restricted to authenticated users.

drop policy if exists "Authenticated users can read message attachments"
on storage.objects;

create policy "Authenticated users can read message attachments"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'message-attachments'
);

-- Users may delete files from their own storage folder.

drop policy if exists "Users can delete their message attachments"
on storage.objects;

create policy "Users can delete their message attachments"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'message-attachments'
  and owner_id = auth.uid()::text
);
