-- ZakiChat Phase 6.1
-- Notifications and unread notification foundation.

-- =========================================================
-- NOTIFICATIONS
-- =========================================================

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  actor_id uuid
    references auth.users(id)
    on delete set null,

  conversation_id uuid
    references public.conversations(id)
    on delete cascade,

  message_id uuid
    references public.messages(id)
    on delete cascade,

  type text not null default 'message',

  title text not null,
  body text,

  read_at timestamptz,

  created_at timestamptz not null default now(),

  constraint notifications_type_check
    check (
      type in (
        'message',
        'mention',
        'reply',
        'reaction',
        'system'
      )
    )
);

-- =========================================================
-- INDEXES
-- =========================================================

create index if not exists notifications_user_created_at_idx
on public.notifications(user_id, created_at desc);

create index if not exists notifications_user_unread_idx
on public.notifications(user_id, created_at desc)
where read_at is null;

create index if not exists notifications_conversation_id_idx
on public.notifications(conversation_id);

create index if not exists notifications_message_id_idx
on public.notifications(message_id);

create index if not exists notifications_actor_id_idx
on public.notifications(actor_id);

-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table public.notifications enable row level security;

drop policy if exists "Users can view their notifications"
on public.notifications;

create policy "Users can view their notifications"
on public.notifications
for select
to authenticated
using (
  user_id = auth.uid()
);

drop policy if exists "Users can mark their notifications as read"
on public.notifications;

create policy "Users can mark their notifications as read"
on public.notifications
for update
to authenticated
using (
  user_id = auth.uid()
)
with check (
  user_id = auth.uid()
);

-- Clients should not directly create notifications.
-- Notifications are generated by trusted database functions/triggers.

-- =========================================================
-- MESSAGE NOTIFICATION FUNCTION
-- =========================================================

create or replace function public.create_message_notifications()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin

  insert into public.notifications (
    user_id,
    actor_id,
    conversation_id,
    message_id,
    type,
    title,
    body
  )
  select
    cm.user_id,
    new.sender_id,
    new.conversation_id,
    new.id,
    'message',
    'New message',
    left(new.content, 200)
  from public.conversation_members cm
  where cm.conversation_id = new.conversation_id
    and cm.user_id <> new.sender_id;

  return new;
end;
$$;

-- =========================================================
-- MESSAGE INSERT NOTIFICATION TRIGGER
-- =========================================================

drop trigger if exists messages_create_notifications
on public.messages;

create trigger messages_create_notifications
after insert on public.messages
for each row
execute function public.create_message_notifications();

-- =========================================================
-- REALTIME
-- =========================================================

do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) then

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'notifications'
    ) then

      alter publication supabase_realtime
      add table public.notifications;

    end if;

  end if;
end;
$$;
